export enum OPERATING_SYSTEM {
    MAC = "MAC",
    WINDOWS = "WINDOWS",
    LINUX = "LINUX",
}


export enum JOB_TITLE {
    JUNIOR = "JUNIOR",
    MEDIER = "MEDIER",
    SENIOR = "SENIOR",
    LEAD_DEVELOPER = "LEAD DEVELOPER",
    SITE_RELIABILITY_ENGINEER = "SITE RELIABILITY ENGINEER",
    TECH_LEAD = "TECH_LEAD",
    CTO = "CTO",
}