export enum DANGER_METER {
    BALANCED = "BALANCED",
    UNPREDICTABLE = "UNPREDICTABLE",
    TEAM_PLAYER = "TEAM_PLAYER",
    AGGRESIVE = "AGGRESIVE",
    DEFENSIVE = "DEFENSIVE",
    TECHNICAL = "TECHNICAL",
}

export enum ACTION_TYPES {
    NETWORK = "NETWORK",
    ITEM = "ITEM",
    GIT = "GIT",
    ATTACK = "ATTACK",
    DEFENSE = "DEFENSE",
    SURRENDER = "SURRENDER",
    BATTERY = "BATTERY",
    GLOBAL = "GLOBAL",
}
